return function(self)
    self.TSStrike = { strikethrough = true }
    -- Linked
    self.TSAnnotation = { link = "PreProc" }
    self.TSAttribute = { link = "PreProc" }
    self.TSBoolean = { link = "Boolean" }
    self.TSCharacter = { link = "Character" }
    self.TSCharacterSpecial = { link = "SpecialChar" }
    self.TSComment = { link = "Comment" }
    self.TSConditional = { link = "Conditional" }
    self.TSConstBuiltin = { link = "Builtin" }
    self.TSConstMacro = { link = "Macro" }
    self.TSConstant = { link = "Constant" }
    self.TSConstructor = { link = "Type" }
    self.TSDanger = { link = "DiagnosticVirtualTextError" }
    self.TSDebug = { link = "Debug" }
    self.TSDefine = { link = "Define" }
    self.TSEmphasis = { link = "Italic" }
    self.TSEnvironment = { link = "Macro" }
    self.TSEnvironmentName = { link = "Type" }
    self.TSException = { link = "Exception" }
    self.TSField = { link = "Identifier" }
    self.TSFloat = { link = "Float" }
    self.TSFuncBuiltin = { link = "Builtin" }
    self.TSFuncMacro = { link = "Macro" }
    self.TSFunction = { link = "Function" }
    self.TSInclude = { link = "Include" }
    self.TSKeyword = { link = "Keyword" }
    self.TSKeywordFunction = { link = "Keyword" }
    self.TSKeywordOperator = { link = "TSOperator" }
    self.TSKeywordReturn = { link = "TSKeyword" }
    self.TSLabel = { link = "Label" }
    self.TSLiteral = { link = "String" }
    self.TSMath = { link = "Special" }
    self.TSMethod = { link = "Function" }
    self.TSNamespace = { link = "Include" }
    self.TSNone = { link = "None" }
    self.TSNote = { link = "DiagnosticHint" }
    self.TSNumber = { link = "Number" }
    self.TSOperator = { link = "Operator" }
    self.TSParameter = { link = "Identifier" }
    self.TSParameterReference = { link = "TSParameter" }
    self.TSPlaygroundFocus = { link = "Visual" }
    self.TSPlaygroundLang = { link = "String" }
    self.TSPreProc = { link = "PreProc" }
    self.TSProperty = { link = "Identifier" }
    self.TSPunctBracket = { link = "Delimiter" }
    self.TSPunctDelimiter = { link = "Delimiter" }
    self.TSPunctSpecial = { link = "Keyword" }
    self.TSQueryLinterError = { link = "Error" }
    self.TSRepeat = { link = "Repeat" }
    self.TSStorageClass = { link = "StorageClass" }
    self.TSString = { link = "String" }
    self.TSStringEscape = { link = "SpecialKey" }
    self.TSStringRegex = { link = "String" }
    self.TSStringSpecial = { link = "SpecialChar" }
    self.TSStrong = { link = "Bold" }
    self.TSSymbol = { link = "Identifier" }
    self.TSTag = { link = "Label" }
    self.TSTagAttribute = { link = "TSProperty" }
    self.TSTagDelimiter = { link = "Delimiter" }
    self.TSText = { link = "TSNone" }
    self.TSTextReference = { link = "Constant" }
    self.TSTitle = { link = "Title" }
    self.TSTodo = { link = "Todo" }
    self.TSType = { link = "Type" }
    self.TSTypeBuiltin = { link = "Builtin" }
    self.TSTypeDefinition = { link = "Typedef" }
    self.TSTypeQualifier = { link = "Type" }
    self.TSURI = { link = "Underlined" }
    self.TSUnderline = { link = "Underlined" }
    self.TSVariable = { link = "Normal" }
    self.TSVariableBuiltin = { link = "Builtin" }
    self.TSWarning = { link = "DiagnosticWarn" }
end
