#!/usr/bin/env dash

OPERANDI='operandi'
VIVENDI='vivendi'

source_file() {
    printf '%s/modus-themes/modus-themes.el' "$(git rev-parse --show-toplevel)"
}

extract_variables() {
    emacs -Q --batch --load "$(source_file)" --load 'extract.el'
}

convert_to_lua() {
    sed -E \
        -e 's/\)+"?/",\n/g' \
        -e 's/[" ]?\(+//g' \
        -e 's/-/_/g' \
        -e 's/\. /= "/g' \
        "$1"
}

return_table() {
    xargs -0 printf 'return {%s}\n'
}

generate_palette() {
    convert_to_lua "$1" | sort | return_table | stylua -s -
}

generate() {
    lua_file="${1}.lua"
    elisp_file="${1}.el"

    generate_palette "$elisp_file" >"$lua_file"
    rm "$elisp_file"
}

main() {
    extract_variables

    generate "$OPERANDI"
    generate "$VIVENDI"
}

main
